# Generated by Django 4.1 on 2025-01-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_clasificacion_updated_estado_updated_marca_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AddField(
            model_name='producto',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
