# Generated by Django 4.1 on 2025-01-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ubicacion_options_producto_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
