# Generated by Django 4.1 on 2025-01-07 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('photo', models.ImageField(upload_to='', verbose_name='Foto')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('brand', models.ManyToManyField(to='core.marca', verbose_name='Marca')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clasificacion', verbose_name='Categoría')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion', verbose_name='Ubicación')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitante', verbose_name='Solicitante')),
                ('state', models.ManyToManyField(to='core.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
