# Generated by Django 4.1 on 2025-01-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='requestor',
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('returned', models.DateTimeField(verbose_name='Fecha de Devolución')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitante', verbose_name='Solicitante')),
            ],
        ),
    ]
