# Generated by Django 4.1 on 2025-01-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_clasificacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='product',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='requestor',
        ),
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Lugar'),
        ),
        migrations.DeleteModel(
            name='Solicitante',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
