# Generated by Django 5.1.7 on 2025-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_solicitante_solicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad",
            field=models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AddField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código de Barras",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="es_consumible",
            field=models.BooleanField(default=False, verbose_name="Es Consumible"),
        ),
    ]
