# Generated by Django 5.1.7 on 2025-04-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_solicitante_solicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="es_consumible",
            field=models.BooleanField(default=False, verbose_name="Es Consumible"),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Stock Disponible"
            ),
        ),
    ]
