# Generated by Django 5.1.7 on 2025-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_producto_es_consumible_producto_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código de Barras",
            ),
        ),
    ]
