# Generated by Django 5.1.7 on 2025-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_producto_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
