# Generated by Django 5.1.7 on 2025-04-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_producto_cantidad_producto_codigo_barras_and_more"),
        ("core", "0011_alter_producto_barcode"),
    ]

    operations = []
