# Generated by Django 5.1.7 on 2025-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_merge_20250415_1053"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="codigo_barras",
        ),
        migrations.AlterField(
            model_name="producto",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Código de Barras",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad Disponible"
            ),
        ),
    ]
