# Generated by Django 5.1.7 on 2025-05-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_producto_cantidad_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="es_consumible",
        ),
        migrations.AddField(
            model_name="clasificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("dispositivo", "Dispositivo"),
                    ("consumible", "Consumible"),
                    ("herramienta", "Herramienta"),
                ],
                default="dispositivo",
                max_length=20,
                verbose_name="Tipo de Categoría",
            ),
        ),
    ]
