# Generated by Django 5.1.7 on 2025-05-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_producto_es_consumible_clasificacion_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("dispositivo", "Dispositivo"),
                    ("consumible", "Consumible"),
                    ("herramienta", "Herramienta"),
                ],
                default="dispositivo",
                max_length=20,
                verbose_name="Tipo de Producto",
            ),
        ),
    ]
