# Generated by Django 5.1.7 on 2025-05-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_producto_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="classification",
        ),
    ]
