# Generated by Django 5.1 on 2025-06-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_producto_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
