# Generated by Django 5.1 on 2025-06-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_solicitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
