# Generated by Django 5.2.5 on 2025-10-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_item',
            field=models.CharField(choices=[('kit', 'Kit'), ('individual', 'Individual')], default='individual', max_length=20, verbose_name='Tipo de Ítem'),
        ),
    ]
