# Generated by Django 5.2.5 on 2025-11-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='core.producto'),
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='cantidad_actual',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='cantidad_real',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='nombre',
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='elemento',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pertenece_a_kits', to='core.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Edición'),
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
    ]
