# Generated by Django 5.2.5 on 2025-11-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_elemento_kit_remove_elemento_cantidad_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='producto',
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_real',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_despacho', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='core.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='elemento',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='core.kit'),
        ),
    ]
