# Generated by Django 5.2.5 on 2025-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_elemento_kit_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='producto',
        ),
        migrations.AddField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del elemento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
