# Generated by Django 5.2.5 on 2025-11-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_elemento_producto_elemento_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='itemcotizacion',
            options={'verbose_name': 'Item de Cotización', 'verbose_name_plural': 'Items de Cotización'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='solicitante',
            options={'verbose_name': 'Solicitante', 'verbose_name_plural': 'Solicitantes'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elemento',
            name='cantidad_real',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='tipo',
            field=models.CharField(choices=[('dispositivo', 'Dispositivo'), ('consumible', 'Consumible'), ('herramienta', 'Herramienta')], default='dispositivo', max_length=20, verbose_name='Tipo de Categoría'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='brand',
            field=models.ManyToManyField(to='core.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='state',
            field=models.ManyToManyField(to='core.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('dispositivo', 'Dispositivo'), ('consumible', 'Consumible'), ('herramienta', 'Herramienta')], default='dispositivo', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_item',
            field=models.CharField(choices=[('kit', 'Kit'), ('individual', 'Individual')], default='individual', max_length=20, verbose_name='Tipo de Ítem'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='mail',
            field=models.EmailField(max_length=40, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='product',
            field=models.ManyToManyField(to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='requested',
            field=models.DateTimeField(verbose_name='Fecha de Préstamo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitante', verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Edición'),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_despacho', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='core.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='elemento',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='core.kit'),
        ),
    ]
