# Generated by Django 5.2.5 on 2025-11-14 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_elemento_kit_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='itemcotizacion',
            options={'verbose_name': 'Item Cotización', 'verbose_name_plural': 'Items Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='itemordencompra',
            options={'verbose_name': 'Item Orden de Compra', 'verbose_name_plural': 'Items Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion'),
        ),
        migrations.AlterField(
            model_name='itemordencompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ordencompra'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        # Nota: SolicitudProducto se creará en la migración 0032
        # No podemos cambiar ManyToManyField a través de AlterField
    ]
