# Generated by Django 5.2.5 on 2025-11-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cotizacion'),
        ),
        migrations.AlterField(
            model_name='itemordencompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordencompra'),
        ),
        # Nota: SolicitudProducto se creará en la migración 0032
        migrations.AlterField(
            model_name='ubicacion',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
