# Generated by Django 5.2.5 on 2025-11-18 02:09

import django.db.models.deletion
from django.db import migrations, models


def migrate_solicitud_products(apps, schema_editor):
    """Migra los productos existentes de ManyToMany a SolicitudProducto"""
    Solicitud = apps.get_model('core', 'Solicitud')
    SolicitudProducto = apps.get_model('core', 'SolicitudProducto')
    Producto = apps.get_model('core', 'Producto')
    
    # Para cada solicitud existente, crear registros en SolicitudProducto
    for solicitud in Solicitud.objects.all():
        # Obtener productos relacionados a través de la tabla intermedia antigua
        productos = solicitud.product.all()
        for producto in productos:
            # Crear registro en SolicitudProducto con cantidad por defecto 1
            SolicitudProducto.objects.create(
                solicitud=solicitud,
                producto=producto,
                cantidad=1
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_itemcotizacion_cotizacion_and_more'),
    ]

    operations = [
        # Paso 1: Agregar campos nuevos
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('entregada', 'Entregada'), ('devuelta', 'Devuelta'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        # Paso 2: Crear el modelo SolicitudProducto
        migrations.CreateModel(
            name='SolicitudProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle Solicitud',
                'verbose_name_plural': 'Detalles Solicitudes',
                'unique_together': {('solicitud', 'producto')},
            },
        ),
        # Paso 3: Migrar datos existentes
        migrations.RunPython(migrate_solicitud_products, migrations.RunPython.noop),
        # Paso 4: Eliminar el campo ManyToMany antiguo
        migrations.RemoveField(
            model_name='solicitud',
            name='product',
        ),
        # Paso 5: Crear el nuevo ManyToManyField con through
        migrations.AddField(
            model_name='solicitud',
            name='product',
            field=models.ManyToManyField(through='core.SolicitudProducto', to='core.producto'),
        ),
    ]
