# Generated by Django 5.2.5 on 2025-11-18 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_solicitud_estado_solicitud_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='product',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='elemento',
            field=models.ForeignKey(blank=True, help_text='Seleccione un elemento del kit (si aplica).', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.elemento'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Seleccione un producto individual o un kit (según tipo).', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto Individual'), ('kit', 'Kit Completo'), ('elemento', 'Elemento de un Kit')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SolicitudProducto',
        ),
    ]
