# Generated by Django 5.2.5 on 2025-11-18 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_solicitud_product_solicitud_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('dispositivo', 'Dispositivo'), ('consumible', 'Consumible'), ('herramienta', 'Herramienta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='elemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.elemento'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('elemento', 'Elemento')], max_length=20),
        ),
    ]
