# Generated by Django 5.2.5 on 2025-11-21 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_clasificacion_name_alter_estado_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Codigo de barras'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='brand',
            field=models.ManyToManyField(to='core.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='state',
            field=models.ManyToManyField(to='core.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('dispositivo', 'Dispositivo'), ('consumible', 'Consumible'), ('herramienta', 'Herramienta')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_item',
            field=models.CharField(choices=[('kit', 'Kit'), ('individual', 'Individual')], default='individual', max_length=20, verbose_name='Kit/Individual'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='mail',
            field=models.EmailField(max_length=40, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='requested',
            field=models.DateTimeField(verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitante', verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Ubicación'),
        ),
    ]
