# Generated by Django 5.2.5 on 2025-11-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_estado_name_alter_marca_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
