# Generated by Django 5.2.5 on 2025-11-21 03:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_solicitante_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[core.validators.validar_rut], verbose_name='RUT'),
        ),
    ]
