# Generated by Django 5.2.5 on 2025-11-23 11:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_cotizacion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_despacho',
            field=models.DateField(verbose_name='Fecha de Despacho'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(help_text='Formato: 12345678-9', max_length=20, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='rut',
            field=models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, validators=[core.validators.validar_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nombre'),
        ),
    ]
