# Generated by Django 5.2.5 on 2025-11-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_ordencompra_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='elemento',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
