# Generated by Django 5.2.5 on 2025-11-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_solicitud_elemento_remove_solicitud_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('devuelta', 'Devuelta')], default='pendiente', max_length=20),
        ),
    ]
