# Generated by Django 5.2.5 on 2025-11-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='core.proveedor'),
        ),
    ]
