# Generated by Django 5.2.5 on 2025-11-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_ordencompra_cotizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='core.proveedor'),
        ),
    ]
