# Generated by Django 5.2.5 on 2025-11-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_ordencompra_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_plantilla',
            field=models.BooleanField(default=False),
        ),
    ]
