# Generated by Django 5.2.5 on 2025-11-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_producto_es_plantilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_plantilla',
        ),
    ]
