# Generated by Django 5.2.5 on 2025-11-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_producto_es_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fue_clonado',
            field=models.BooleanField(default=False),
        ),
    ]
