# Generated by Django 5.2.5 on 2025-11-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_producto_fue_clonado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fue_clonado',
        ),
    ]
