# Generated by Django 5.2.5 on 2025-11-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_producto_fue_clonado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='numero_factura',
            field=models.CharField(error_messages={'unique': 'Este número de factura ya está registrado.'}, max_length=50, unique=True),
        ),
    ]
