# Generated by Django 5.2.5 on 2025-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_ordencompra_numero_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='itemordencompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemordencompra',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='monto_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
