# Generated by Django 5.2.5 on 2025-11-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_solicitud_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='cantidad_real',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
