# Generated by Django 5.2.5 on 2025-12-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_elemento_cantidad_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='itemcotizacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='itemcotizacion',
            name='producto',
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='nombre_producto',
            field=models.CharField(default='', max_length=25, verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
