# Generated by Django 5.2.5 on 2025-12-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_cotizacion_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordencompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='productos',
        ),
        migrations.AddField(
            model_name='itemordencompra',
            name='nombre_producto',
            field=models.CharField(default='', max_length=200, verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
