# Generated by Django 5.2.5 on 2025-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_itemordencompra_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='referencia',
            field=models.ImageField(blank=True, help_text='Imagen de la orden de compra', null=True, upload_to='ordenes_compra/'),
        ),
    ]
