# Generated by Django 5.2.5 on 2025-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_ordencompra_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='referencia',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='referencia',
            field=models.ImageField(blank=True, null=True, upload_to='ordenes_compra/', verbose_name='Imagen Orden de Compra'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='tipo',
            field=models.CharField(choices=[('dispositivo', 'Dispositivo'), ('consumible', 'Consumible'), ('herramienta', 'Herramienta')], default='dispositivo', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre elemento'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('dispositivo', 'Dispositivo'), ('consumible', 'Consumible'), ('herramienta', 'Herramienta')], max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Ubicación'),
        ),
    ]
