# Generated by Django 5.2.5 on 2025-12-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_ordencompra_referencia_cotizacion_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='referencia',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='referencia',
            field=models.ImageField(blank=True, null=True, upload_to='orden_compra/', verbose_name='Imagen Orden de Compra'),
        ),
    ]
