# Generated by Django 6.0.3 on 2026-03-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_cotizacion_referencia_ordencompra_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
