# Generated by Django 5.2.3 on 2026-03-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_itemcotizacion_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto'),
        ),
    ]
