# Generated by Django 5.2.3 on 2026-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_solicitud_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='producto',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='productos',
            field=models.ManyToManyField(to='core.producto', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ubicación'),
        ),
    ]
