# Generated by Django 6.0.3 on 2026-06-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_solicitud_producto_solicitud_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='kits_generados',
            field=models.BooleanField(default=False),
        ),
    ]
