# Generated by Django 6.0.3 on 2026-06-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_producto_kits_generados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitud')),
            ],
        ),
    ]
