# Generated by Django 6.0.3 on 2026-06-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_itemsolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitud',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
