# Generated by Django 6.0.3 on 2026-06-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_itemsolicitud_procesado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsolicitud',
            options={'verbose_name': 'Item Solicitud', 'verbose_name_plural': 'Items Solicitud'},
        ),
    ]
