# Generated by Django 6.0.6 on 2026-07-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_itemsolicitud_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elemento',
        ),
    ]
