# Generated by Django 4.1 on 2025-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
