# Generated by Django 4.1 on 2025-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_alter_bitacora_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
