# Generated by Django 5.1.7 on 2025-04-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bitacora", "0003_alter_bitacora_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bitacora",
            options={"verbose_name": "Registro", "verbose_name_plural": "Registros"},
        ),
    ]
